name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: "v16.10.0"
    - run: npm run dist
    
    - uses: actions/upload-artifact@v2.2.4
      with:
        path: ./dist.zip
